name: flutter_measure_formatter_web
description: Web platform implementation of flutter_measure_formatter
homepage: https://github.com/rdev-software/flutter_measure_formatter/flutter_measure_formatter_web
# 0.1.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 0.0.3

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterMeasureFormatterPlugin
        fileName: flutter_measure_formatter_web.dart

dependencies:
  flutter_measure_formatter_platform_interface: ^0.0.3
  platform_detect: ^1.4.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.2.2

#dependency_overrides:
#  flutter_measure_formatter_platform_interface:
#    path: ../flutter_measure_formatter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^5.2.5
  pedantic: ^1.8.0
  mockito: ^4.1.1

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"